### ISSUE TITLE
TypeScript definitions missing

### ISSUE THREAD

**Issue by MickL** [ThierrySpetebroot/gulp-fn#4]
Hey,

could you please add TypeScript definitions? Maybe to `@types/gulp-fn`?

<img width="412" alt="bildschirmfoto 2018-06-25 um 15 13 06" src="https://user-images.githubusercontent.com/5103210/41852066-51d25d82-788a-11e8-9cd8-6e95b44ebef2.png">

Thanks!

**Comment by ThierrySpetebroot** [comment]
Hello @MickL,
 I'll try to add them by the end of next week.

Best regards,
 Thierry

**Comment by ThierrySpetebroot** [comment]
Version [`0.0.3`](https://www.npmjs.com/package/gulp-fn/v/0.0.3) now available on NPM.

The definitions are included in the repository (see [`gulp-fn.d.ts`](https://github.com/ThierrySpetebroot/gulp-fn/blob/e5091868da7e55d0834085b169fb02838f13bfb6/gulp-fn.d.ts)) and should be managed automatically by Visual Studio Code.
I'll probably push to [`@types/gulp-fn`](https://github.com/DefinitelyTyped/DefinitelyTyped) the definitions file anyway.

_NOTE_: `gulp-fn` returns a `stream.Transform` as saw in other definition files. `NodeJS.ReadWriteStream` is probably equivalent (as it is used too in gulp plugin definitions).

Let me know if there are issues on this subject in your workflow.
